Dev
KHudali17/Simple-Inventory pull request #1
Opened 2023-07-23 11:10 UTC by KHudali17

2023-07-24 14:06 UTC, MazenAmria requested changes
1. split the commands into separate files but within the same folder and namespace
2. try throwing exceptions for `product not found` and `inventory is empty`, but I'm not sure if this is going to complicate things as we have a common interface for the Command and the invoker is acting on that interface, so it should be aware of the exceptions. @SwishBoy what do you think

2023-07-24 14:06 UTC, MazenAmria commented on Inventory.cs
> +        private List<Product> products;
> Use camel casing ("camelCasing") when naming private or internal fields, and prefix them with _.

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case

2023-07-24 14:06 UTC, MazenAmria commented on Commands.cs
> +        public void Execute()
> Add at least one blank line between method definitions and property definitions

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions

2023-07-24 14:06 UTC, MazenAmria commented on Commands.cs
> +                Console.WriteLine("Inventory is Empty.");
it would be better if you returned the execution to avoid the two-levels nesting
```CSharp
if (isEmpty)
{
    // ...
    return;
}

foreach(...)
{
    // ...
}
```

2023-07-27 07:38 UTC, kshawish commented on AddProductsCommand.cs
> +namespace SimpleInv
let's avoid abbreviations especially when the term is not excessively long. 
we typically reserve abbreviations for terms composed of multiple words and are commonly used within the project domain.

2023-07-27 07:38 UTC, kshawish commented on Inventory.cs
>          public void UpdateProduct(Product product, string newName, decimal newPrice, decimal newQuantity)
Just worndering about the update method here.
Usually I'd expect to pass and object that represent the updated Product to the Inventory update method which will reflect that to the In-Memery/DB product. and not passing each property we wanna update to the update method.

2023-07-27 07:38 UTC, kshawish commented on Inventory.cs
>          public void AddProduct(Product product)
I don't see any validation rules in the Inventory? what if we tried to add a product with negative price ?

2023-07-27 07:47 UTC, kshawish commented on Inventory.cs
> +            return _products.Find(x => x.Name.Equals(productName, StringComparison.OrdinalIgnoreCase));
what if the product is not found will you depend on find throw exception? or do you think it's better to catch it and throw a custom exception?

2023-09-27 11:55 UTC, merged